name: Monitor Noticias

on:
  schedule:
    - cron: "0 */6 * * *"  # Cada 6 horas
  workflow_dispatch:      # Permite ejecutarlo manualmente desde GitHub

jobs:
  run-monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install gspread google-auth pandas feedparser

      # --- PASO CORREGIDO ---
      # Decodifica el secret Base64 para crear el archivo JSON
      - name: Create service account file
        run: echo '${{ secrets.GOOGLE_CREDENTIALS }}' > reporte-seguridad.json

      - name: Run monitor script
        run: python monitor_seguridad.py
